import { Experience } from "@/types";

export const experiencesData: Experience[] = [
  {
    id: "klover-2025",
    company: "Klover AI",
    position: "Software Engineer Intern",
    location: "Remote",
    timeframe: "March 2025 – Present",
    startDate: new Date(2025, 2),
    endDate: null,
    description: "Built AI-powered newsletter platform with ML-based personalization and automated hiring system.",
    technologies: ["Python", "Huggingface", "Selenium", "Next.js", "PostgreSQL"],
    image: "/experiences/klover.webp",
  },
  {
    id: "freelance-kevin-2025",
    company: "Kevin Schoovaerts",
    position: "Freelance Full-stack Developer",
    location: "Remote",
    timeframe: "March 2025 – Present",
    startDate: new Date(2025, 2),
    endDate: null,
    description: "Delivered fintech portfolio platform with real-time market data and Stripe monetization.",
    technologies: ["Typescript", "Next.js", "Stripe", "Supabase", "PostgreSQL", "Agile"],
    image: "/experiences/kevin.webp",
  },
  {
    id: "commons-xr-2024",
    company: "The Commons XR",
    position: "Full-Stack Developer Intern",
    location: "Remote",
    timeframe: "September 2024 – January 2025",
    startDate: new Date(2024, 8),
    endDate: new Date(2025, 0),
    description: "Led data visualization migration from PowerBI to React-based charts for XR platform.",
    technologies: ["React", "Material-UI", "PowerBI", "Data Analytics", "UI/UX"],
    image: "/experiences/commons-xr.webp",
  },
  {
    id: "headstarter-2024",
    company: "Headstarter",
    position: "Software Engineering Fellow",
    location: "Remote",
    timeframe: "June 2024 – September 2024",
    startDate: new Date(2024, 5),
    endDate: new Date(2024, 8),
    description: "Built full-stack AI applications. Finalist in 2 hiring hackathons.",
    technologies: ["Next.js", "Python", "Langchain"],
    image: "/experiences/headstarter.webp",
  },
  {
    id: "mobalytics-2024",
    company: "Extern",
    position: "Mobalytics Remote Extern",
    location: "Remote",
    timeframe: "May 2024 – June 2024",
    startDate: new Date(2024, 4),
    endDate: new Date(2024, 5),
    description: "Top presenter from 412-person cohort. Delivered market analysis for gaming analytics platform.",
    technologies: ["Market Research", "Data Analysis", "Competitive Analysis", "Strategic Planning"],
    image: "/experiences/extern.webp",
  },
];
